import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";

export interface GeneratedDocument {
  buffer: Buffer;
  fileName: string;
  mimeType: string;
  size: number;
  /** True only in mock mode; a real run never labels its output simulated. */
  simulated: boolean;
}

const DOCX_MIME =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

/** Turns generated markdown-ish text into ordered DOCX blocks. */
export function toBlocks(text: string): Paragraph[] {
  const blocks: Paragraph[] = [];

  for (const raw of text.split(/\n/)) {
    const line = raw.trim();
    if (!line) continue;

    const heading = /^(#{1,4})\s+(.*)$/.exec(line);
    if (heading) {
      const level = heading[1].length;
      blocks.push(new Paragraph({
        text: heading[2],
        heading: level === 1 ? HeadingLevel.HEADING_1
          : level === 2 ? HeadingLevel.HEADING_2
          : level === 3 ? HeadingLevel.HEADING_3 : HeadingLevel.HEADING_4,
      }));
      continue;
    }

    const bullet = /^[-*•]\s+(.*)$/.exec(line);
    if (bullet) {
      blocks.push(new Paragraph({ text: bullet[1], bullet: { level: 0 } }));
      continue;
    }

    const numbered = /^\d+[.)]\s+(.*)$/.exec(line);
    if (numbered) {
      blocks.push(new Paragraph({
        text: numbered[1], numbering: { reference: "dotai-numbered", level: 0 },
      }));
      continue;
    }

    // Bold runs are the only inline formatting worth carrying across.
    const runs: TextRun[] = [];
    const parts = line.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
    for (const part of parts) {
      const bold = /^\*\*([^*]+)\*\*$/.exec(part);
      runs.push(bold ? new TextRun({ text: bold[1], bold: true }) : new TextRun(part));
    }
    blocks.push(new Paragraph({ children: runs }));
  }

  if (blocks.length === 0) blocks.push(new Paragraph(""));
  return blocks;
}

export function safeDocName(title: string): string {
  const clean = title
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60) || "dotai-document";
  return `${clean}.docx`;
}

/**
 * Renders governed content into a structurally valid DOCX.
 *
 * This produces a real OOXML package via the `docx` library - not text with a
 * .docx extension. Callers must only reach here after ControlPlane has allowed
 * the content: a blocked answer must never become a downloadable artefact.
 */
export async function generateDocx(input: {
  title: string;
  content: string;
  /** Rendered as a footer note, e.g. a HOLD or simulation caveat. */
  notice?: string;
  simulated?: boolean;
}): Promise<GeneratedDocument> {
  const children: Paragraph[] = [
    new Paragraph({ text: input.title, heading: HeadingLevel.TITLE }),
    ...toBlocks(input.content),
  ];

  if (input.notice) {
    children.push(new Paragraph({ text: "" }));
    children.push(new Paragraph({
      children: [new TextRun({ text: input.notice, italics: true, size: 18 })],
    }));
  }

  const doc = new Document({
    creator: "dotAI",
    title: input.title,
    description: "Generated by dotAI ControlPlane",
    numbering: {
      config: [{
        reference: "dotai-numbered",
        levels: [{ level: 0, format: "decimal", text: "%1.", alignment: "start" }],
      }],
    },
    sections: [{ children }],
  });

  const buffer = await Packer.toBuffer(doc);
  return {
    buffer: Buffer.from(buffer),
    fileName: safeDocName(input.title),
    mimeType: DOCX_MIME,
    size: buffer.byteLength,
    simulated: Boolean(input.simulated),
  };
}

/** A DOCX is a ZIP package; this is a cheap structural sanity check. */
export function isValidDocx(buffer: Buffer): boolean {
  return buffer.length > 1000 && buffer.subarray(0, 2).toString("latin1") === "PK";
}
